"""Repository factory that wraps VersionedMongoCRUD behind the RepositoryPort interface.

Usage::

    RepoClass = RepositoryFactory.create(
        schema_name="widget",
        doc_model=WidgetDocument,
        create_model=WidgetCreate,
        update_model=WidgetUpdate,
    )
    repo = RepoClass(db=motor_database)
"""

from __future__ import annotations

from typing import Any, Type

from motor.motor_asyncio import AsyncIOMotorDatabase
from pydantic import BaseModel

from slip_stream.adapters.persistence.db.generic_crud import VersionedMongoCRUD
from slip_stream.core.domain.base import BaseDocument


class RepositoryFactory:
    """Factory that generates a concrete MongoRepository class for a given schema.

    The returned class wraps VersionedMongoCRUD and satisfies RepositoryPort
    without explicitly inheriting from it (structural subtyping via Protocol).
    """

    @classmethod
    def create(
        cls,
        schema_name: str,
        doc_model: Type[BaseDocument],
        create_model: Type[BaseModel],
        update_model: Type[BaseModel],
    ) -> Type[Any]:
        """Return a new MongoRepository class bound to the given models.

        Parameters:
            schema_name: Snake-case name of the entity (also used as the
                MongoDB collection name).
            doc_model: Pydantic model class that extends BaseDocument.
            create_model: Pydantic model class used for creation payloads.
            update_model: Pydantic model class used for update payloads.

        Returns:
            A class whose constructor accepts a single ``db`` argument
            and exposes the five RepositoryPort methods.
        """
        _schema_name = schema_name
        _doc_model = doc_model
        _create_model = create_model
        _update_model = update_model

        class MongoRepository:
            """Concrete MongoDB-backed repository generated by RepositoryFactory."""

            def __init__(self, db: AsyncIOMotorDatabase) -> None:
                self._crud: VersionedMongoCRUD[Any, Any, Any] = VersionedMongoCRUD(
                    db=db,
                    collection_name=_schema_name,
                    model=_doc_model,
                    create_model=_create_model,
                    update_model=_update_model,
                )

            async def create(self, data: Any, user_id: str | None = None) -> Any:
                """Create a new document via VersionedMongoCRUD."""
                return await self._crud.create(data=data, user_id=user_id)

            async def get_by_entity_id(self, entity_id: Any) -> Any | None:
                """Return the latest active document version for entity_id."""
                return await self._crud.get_by_entity_id(entity_id=entity_id)

            async def list_latest_active(
                self,
                skip: int = 0,
                limit: int = 100,
                sort_by: str = "created_at",
                sort_order: int = -1,
                filter_criteria: dict[str, Any] | None = None,
            ) -> list[Any]:
                """Return paginated latest active document versions."""
                return await self._crud.list_latest_active(
                    skip=skip,
                    limit=limit,
                    sort_by=sort_by,
                    sort_order=sort_order,
                    filter_criteria=filter_criteria,
                )

            async def update_by_entity_id(
                self,
                entity_id: Any,
                data: Any,
                user_id: str | None = None,
            ) -> Any | None:
                """Create a new document version with the applied changes."""
                return await self._crud.update_by_entity_id(
                    entity_id=entity_id, data=data, user_id=user_id
                )

            async def delete_by_entity_id(
                self, entity_id: Any, user_id: str | None = None
            ) -> Any | None:
                """Soft-delete by creating a tombstone document version."""
                return await self._crud.delete_by_entity_id(
                    entity_id=entity_id, user_id=user_id
                )

        pascal = "".join(word.capitalize() for word in schema_name.split("_"))
        MongoRepository.__name__ = f"{pascal}MongoRepository"
        MongoRepository.__qualname__ = f"{pascal}MongoRepository"

        return MongoRepository
