"""Repository factory for SQL-backed entities.

Mirrors ``RepositoryFactory`` (MongoDB) but wraps ``SQLRepository`` with a
pre-bound SQLAlchemy table.  The returned class takes a single ``db`` arg
(``AsyncSession``) so that ``registration.repository_class(ctx.db)`` works
identically for both backends.

Usage::

    RepoClass = SQLRepositoryFactory.create(
        schema_name="widget",
        table=widget_table,
        doc_model=WidgetDocument,
        create_model=WidgetCreate,
        update_model=WidgetUpdate,
    )
    repo = RepoClass(db=async_session)
"""

from __future__ import annotations

from typing import Any, Type

from pydantic import BaseModel

from slip_stream.core.domain.base import BaseDocument


class SQLRepositoryFactory:
    """Factory that generates a concrete SQL repository class for a given schema.

    The returned class wraps ``SQLRepository`` with table and doc_model
    pre-bound via closure, and satisfies ``RepositoryPort`` via structural
    subtyping.
    """

    @classmethod
    def create(
        cls,
        schema_name: str,
        table: Any,
        doc_model: Type[BaseDocument],
        create_model: Type[BaseModel],
        update_model: Type[BaseModel],
    ) -> Type[Any]:
        """Return a new SQLBoundRepository class with the table pre-bound.

        Parameters:
            schema_name: Snake-case name of the entity.
            table: A SQLAlchemy ``Table`` object for the entity.
            doc_model: Pydantic document model (extends BaseDocument).
            create_model: Pydantic model for creation payloads.
            update_model: Pydantic model for update payloads.

        Returns:
            A class whose constructor accepts a single ``db`` argument
            (``AsyncSession``) and exposes the five RepositoryPort methods.
        """
        _table = table
        _doc_model = doc_model

        class SQLBoundRepository:
            """Concrete SQL-backed repository generated by SQLRepositoryFactory."""

            def __init__(self, db: Any) -> None:
                from slip_stream.adapters.persistence.db.sql_repository import (
                    SQLRepository,
                )

                self._repo = SQLRepository(
                    session=db, table=_table, doc_model=_doc_model
                )

            async def create(self, data: Any, user_id: str | None = None) -> Any:
                """Create a new document via SQLRepository."""
                return await self._repo.create(data=data, user_id=user_id)

            async def get_by_entity_id(self, entity_id: Any) -> Any | None:
                """Return the latest active document version for entity_id."""
                return await self._repo.get_by_entity_id(entity_id=entity_id)

            async def list_latest_active(
                self,
                skip: int = 0,
                limit: int = 100,
                sort_by: str = "created_at",
                sort_order: int = -1,
                filter_criteria: dict[str, Any] | None = None,
            ) -> list[Any]:
                """Return paginated latest active document versions."""
                return await self._repo.list_latest_active(
                    skip=skip,
                    limit=limit,
                    sort_by=sort_by,
                    sort_order=sort_order,
                    filter_criteria=filter_criteria,
                )

            async def update_by_entity_id(
                self,
                entity_id: Any,
                data: Any,
                user_id: str | None = None,
            ) -> Any | None:
                """Create a new document version with the applied changes."""
                return await self._repo.update_by_entity_id(
                    entity_id=entity_id, data=data, user_id=user_id
                )

            async def count_active(
                self,
                filter_criteria: dict[str, Any] | None = None,
            ) -> int:
                """Count the total active entities matching the filter."""
                return await self._repo.count_active(
                    filter_criteria=filter_criteria,
                )

            async def delete_by_entity_id(
                self, entity_id: Any, user_id: str | None = None
            ) -> Any | None:
                """Soft-delete by creating a tombstone document version."""
                return await self._repo.delete_by_entity_id(
                    entity_id=entity_id, user_id=user_id
                )

        pascal = "".join(word.capitalize() for word in schema_name.split("_"))
        SQLBoundRepository.__name__ = f"{pascal}SQLRepository"
        SQLBoundRepository.__qualname__ = f"{pascal}SQLRepository"
        SQLBoundRepository._is_auto_generated = True  # type: ignore[attr-defined]

        return SQLBoundRepository
