"""Order business logic — wires shipping adapter into the CRUD lifecycle.

This module demonstrates how slip-stream's decorator system connects
domain logic to driven adapters across hex boundaries:

    HTTP Request
        → FastAPI endpoint (auto-generated by slip-stream)
            → @guard: validates pet exists before accepting order
            → @validate: checks quantity limits
            → @transform(when="before"): sets computed fields
            → default create service (auto-generated CRUD)
            → @transform(when="after"): triggers shipping via adapter
            → @on("post_create"): audit logging

The shipping adapter is injected via ``ctx.extras`` during app startup,
keeping the decorator functions decoupled from concrete adapter choice.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from slip_stream import HookError, RequestContext, SlipStreamRegistry

if TYPE_CHECKING:
    from examples.quickstart.advanced.ports import ShippingPort

logger = logging.getLogger(__name__)


def register_order_logic(registry: SlipStreamRegistry) -> None:
    """Register all order business rules with the slip-stream registry.

    Called during app startup. Each decorator hooks into the order
    schema's lifecycle at a specific point.
    """

    # -----------------------------------------------------------------
    # Guard: Verify the pet exists before accepting an order
    # -----------------------------------------------------------------
    @registry.guard("order", "create")
    async def pet_must_exist(ctx: RequestContext) -> None:
        """Reject orders for non-existent pets.

        This guard runs before any other logic. It reaches into the
        database (available via ``ctx.db``) to verify the foreign key.

        Guards raise ``HookError`` to abort the request with a specific
        HTTP status code and message.
        """
        pet_id = ctx.data.pet_id
        if pet_id is None:
            raise HookError(422, "pet_id is required")

        # Query the pet collection directly (cross-schema lookup)
        pet_doc = await ctx.db["pet"].find_one(
            {"entity_id": str(pet_id), "deleted_at": None},
            sort=[("record_version", -1)],
        )
        if pet_doc is None:
            raise HookError(404, f"Pet {pet_id} not found")

        # Stash the pet for downstream use (transforms, hooks)
        ctx.extras["pet_doc"] = pet_doc

    # -----------------------------------------------------------------
    # Validator: Business rules on the order data
    # -----------------------------------------------------------------
    @registry.validate("order", "create", "update")
    async def quantity_limits(ctx: RequestContext) -> None:
        """Enforce business rules that go beyond JSON Schema validation.

        JSON Schema handles type/format validation. Cross-field and
        business-logic checks happen here.
        """
        if ctx.data is None:
            return
        quantity = getattr(ctx.data, "quantity", None)
        if quantity is not None and quantity > 10:
            raise HookError(422, "Cannot order more than 10 pets at once")

    # -----------------------------------------------------------------
    # Transform (before): Compute fields before persistence
    # -----------------------------------------------------------------
    @registry.transform("order", "create", when="before")
    async def set_initial_status(ctx: RequestContext) -> None:
        """Set computed fields that the client doesn't control.

        Transforms mutate ``ctx.data`` in place. 'before' transforms
        run after guards and validators but before the service writes
        to the database.
        """
        ctx.data.status = "placed"
        ctx.data.complete = False

    # -----------------------------------------------------------------
    # Transform (after): Trigger shipping via the adapter
    # -----------------------------------------------------------------
    @registry.transform("order", "create", when="after")
    async def trigger_shipping(ctx: RequestContext) -> None:
        """Submit the order to the shipping provider after persistence.

        This is the hex-boundary crossing point. The transform:
        1. Reads the domain result (``ctx.result``)
        2. Builds a domain transfer object (``ShipmentRequest``)
        3. Calls the shipping port (injected via ``ctx.extras``)
        4. Stashes the tracking info back in extras

        The transform doesn't know *which* shipping adapter is behind
        the port — could be ShipStation, a stub, or any implementation.
        """
        shipping: ShippingPort = ctx.extras.get("shipping_adapter")
        if shipping is None:
            logger.warning("No shipping adapter configured — skipping shipment")
            return

        from examples.quickstart.advanced.ports import ShipmentRequest

        pet_doc = ctx.extras.get("pet_doc", {})
        request = ShipmentRequest(
            order_entity_id=ctx.result.entity_id,
            pet_name=pet_doc.get("name", "Unknown Pet"),
            quantity=ctx.result.quantity,
            customer_id=str(ctx.current_user.get("id", "anonymous")),
        )

        try:
            result = await shipping.create_shipment(request)
            ctx.extras["tracking_number"] = result.tracking_number
            ctx.extras["carrier"] = result.carrier
            logger.info(
                "Shipment created: %s via %s (order %s)",
                result.tracking_number,
                result.carrier,
                ctx.result.entity_id,
            )
        except Exception:
            # Shipping failure is non-fatal — order is already persisted
            logger.exception("Shipping failed for order %s", ctx.result.entity_id)

    # -----------------------------------------------------------------
    # Event hook: Audit trail
    # -----------------------------------------------------------------
    @registry.on("post_create", schema="order")
    async def audit_order_created(ctx: RequestContext) -> None:
        """Log order creation for the audit trail.

        ``@on`` hooks run after all transforms. They're fire-and-forget
        side effects — ideal for logging, metrics, and notifications.
        """
        tracking = ctx.extras.get("tracking_number", "pending")
        logger.info(
            "ORDER CREATED: entity_id=%s, pet=%s, qty=%d, tracking=%s",
            ctx.result.entity_id,
            ctx.extras.get("pet_doc", {}).get("name", "?"),
            ctx.result.quantity,
            tracking,
        )

    # -----------------------------------------------------------------
    # Guard on delete: Only cancel orders that haven't shipped
    # -----------------------------------------------------------------
    @registry.guard("order", "delete")
    async def prevent_shipped_delete(ctx: RequestContext) -> None:
        """Block deletion of orders that have already been delivered."""
        if ctx.entity and ctx.entity.status == "delivered":
            raise HookError(409, "Cannot cancel a delivered order")
